# Explore Metadata to isolate specific cell populations

for more informative or less confounded conclusions

In [1]:
# Load Meta Data
import os
import pandas as pd

save_path = '/media/rohola/ssd_storage/primary_metadata/'; print(len(os.listdir(save_path)))
files = sorted(os.listdir(save_path))
df = pd.concat([pd.read_pickle(save_path+f) for f in files], ignore_index=True)

36

In [3]:
import json
project_path = "/media/lleger/LaCie/mit/disease_geometry/"
diseases = json.load(open(project_path + 'diseases.json'))['diseases']
print(diseases)
diseases = ['small cell lung carcinoma', 'lung large cell carcinoma', 'non-small cell lung carcinoma', 'glioblastoma', 'lung adenocarcinoma',
             ] + ['Parkinson disease', 'Alzheimer disease', 'dementia', 'Lewy body dementia'] + ["dilated cardiomyopathy", "myocardial infarction"] + ['chronic kidney disease', "clear cell renal carcinoma"]
            
dtest = df[int(0.7*len(df)):]
for disease in diseases:
    print(disease)
    display(dtest[dtest['disease'] == disease][['cell_type']].value_counts().reset_index().head(10))

['normal', 'COVID-19', 'glioblastoma', 'dementia', 'lung adenocarcinoma', 'systemic lupus erythematosus', 'dilated cardiomyopathy', 'Crohn disease', 'clear cell renal carcinoma', 'squamous cell lung carcinoma', 'nonpapillary renal cell carcinoma', 'epilepsy', 'breast cancer', 'gastric cancer', 'non-small cell lung carcinoma', 'arrhythmogenic right ventricular cardiomyopathy', 'chronic kidney disease', 'acute kidney failure', 'follicular lymphoma', 'myocardial infarction', 'B-cell acute lymphoblastic leukemia', 'blastoma', 'Parkinson disease', 'B-cell non-Hodgkin lymphoma', 'plasma cell myeloma', 'respiratory system disorder', 'post-COVID-19 disorder', 'small cell lung carcinoma', 'pulmonary fibrosis', 'interstitial lung disease', 'digestive system disorder', 'periodontitis', 'Lewy body dementia', 'gastritis', 'gastric intestinal metaplasia', 'common variable immunodeficiency', 'benign prostatic hyperplasia', 'influenza', 'Crohn ileitis', 'pneumonia', 'pulmonary emphysema', 'chronic rhinitis', 'chronic obstructive pulmonary disease', 'kidney oncocytoma', 'type 2 diabetes mellitus', 'acute myeloid leukemia', 'trisomy 18', 'lung large cell carcinoma', 'Alzheimer disease', 'adenocarcinoma']
small cell lung carcinoma

          cell_type      0
0   epithelial cell  16327
1            T cell   4532
2    dendritic cell    443
3        macrophage    280
4        fibroblast    241
5            B cell    238
6        neutrophil    187
7  endothelial cell    169
8         mast cell     28
9       plasma cell      9

lung large cell carcinoma

                         cell_type     0
0                      native cell  2785
1  CD8-positive, alpha-beta T cell   944
2  CD4-positive, alpha-beta T cell   911
3                           B cell   478
4         nasal mucosa goblet cell   269
5                      plasma cell   151
6               type II pneumocyte   146
7              elicited macrophage   113
8              natural killer cell   105
9                        mast cell    91

non-small cell lung carcinoma

                         cell_type     0
0  CD4-positive, alpha-beta T cell  7958
1  CD8-positive, alpha-beta T cell  6037
2                       macrophage  3876
3                           B cell  3593
4                   malignant cell  3466
5              alveolar macrophage  3055
6                      plasma cell  2894
7                regulatory T cell  2776
8              natural killer cell  1205
9               classical monocyte  1087

glioblastoma

                        cell_type       0
0                  malignant cell  133719
1                      macrophage   81839
2                 microglial cell   59929
3                   mature T cell   32810
4                 oligodendrocyte   12279
5                        monocyte   11784
6  oligodendrocyte precursor cell    6671
7                  dendritic cell    2531
8                      mural cell    1958
9                endothelial cell    1607

lung adenocarcinoma

                         cell_type      0
0  CD4-positive, alpha-beta T cell  45483
1  CD8-positive, alpha-beta T cell  33763
2                           T cell  22651
3              alveolar macrophage  19499
4                           B cell  19036
5                       macrophage  18967
6              natural killer cell  13783
7                   malignant cell  11819
8                  epithelial cell  10325
9               classical monocyte  10123

Parkinson disease

                        cell_type      0
0                 oligodendrocyte  15504
1                          neuron  10685
2                       astrocyte   6020
3                 microglial cell   1829
4  oligodendrocyte precursor cell   1263
5             dopaminergic neuron   1112
6                endothelial cell    977

Alzheimer disease

         cell_type      0
0           neuron  14931
1  microglial cell   3376
2           T cell      4
3         monocyte      4
4      neural cell      2

dementia

                                           cell_type       0
0  L2/3-6 intratelencephalic projecting glutamate...  143271
1                                    oligodendrocyte   28409
2               pvalb GABAergic cortical interneuron   24689
3                 vip GABAergic cortical interneuron   24672
4                   astrocyte of the cerebral cortex   22409
5               lamp5 GABAergic cortical interneuron   18407
6                 sst GABAergic cortical interneuron   14264
7                                    microglial cell   11491
8                     oligodendrocyte precursor cell    7093
9                sncg GABAergic cortical interneuron    5694

Lewy body dementia

                        cell_type      0
0                 oligodendrocyte  10770
1                          neuron   4861
2                       astrocyte   3353
3             dopaminergic neuron   1445
4                 microglial cell   1060
5  oligodendrocyte precursor cell    812
6                endothelial cell    423

dilated cardiomyopathy

                      cell_type      0
0           cardiac muscle cell  42532
1                    mural cell  28596
2  fibroblast of cardiac tissue  24684
3              endothelial cell  24510
4                  myeloid cell  12191
5                   native cell   9512
6                    lymphocyte   3124
7                cardiac neuron   1714
8                      fat cell    307
9                     mast cell    200

myocardial infarction

                                       cell_type      0
0                        cardiac muscle myoblast  13214
1                   fibroblast of cardiac tissue  10721
2                       cardiac endothelial cell   8304
3                  immature innate lymphoid cell   6784
4                                       pericyte   2762
5    lymphoid lineage restricted progenitor cell   1388
6                         smooth muscle myoblast    727
7                                    native cell    652
8                         neuronal receptor cell    511
9  adipocyte of epicardial fat of left ventricle    150

chronic kidney disease

                                           cell_type      0
0  kidney loop of Henle thick ascending limb epit...  10672
1                 epithelial cell of proximal tubule   9446
2              kidney collecting duct principal cell   3933
3                                          leukocyte   3291
4                                   endothelial cell   2847
5           kidney collecting duct intercalated cell   2048
6  kidney loop of Henle thin ascending limb epith...   1446
7  kidney loop of Henle thin descending limb epit...   1321
8                     kidney interstitial fibroblast   1316
9    kidney distal convoluted tubule epithelial cell   1109

clear cell renal carcinoma

                                           cell_type      0
0                                      abnormal cell  11860
1                    CD4-positive, alpha-beta T cell   8466
2  naive thymus-derived CD8-positive, alpha-beta ...   5120
3                                   mature NK T cell   4508
4                                   endothelial cell   3703
5                                 myofibroblast cell   3332
6                                       naive T cell   3313
7                                        native cell   3089
8   activated CD4-positive, alpha-beta T cell, human   2686
9              CD14-positive, CD16-positive monocyte   2568

In [ ]:
# Lewy body dementia astrocyte

# glioblastoma microglial cell

# non-small cell lung carcinoma B cell	

# myocardial infarction cardiac endothelial cell

In [5]:
dtest[(dtest['disease'] == "normal") & (dtest['tissue_general'] == "lung")].value_counts(["cell_type"]).reset_index().head(20)

                                          cell_type      0
0                               alveolar macrophage  43084
1        epithelial cell of lower respiratory tract  32786
2                                      stromal cell  26855
3                                type II pneumocyte  23338
4                                       native cell  17948
5                                  mesenchymal cell  12722
6                                        macrophage  12002
7                                classical monocyte  11981
8                               natural killer cell   7892
9                                          monocyte   7296
10                  CD4-positive, alpha-beta T cell   6942
11              epithelial cell of alveolus of lung   6711
12                               fibroblast of lung   6222
13                  CD8-positive, alpha-beta T cell   5838
14                                       fibroblast   5688
15  ciliated columnar cell of tracheobronchial tree   5230
16                endothelial cell of vascular tree   4999
17                                type I pneumocyte   4912
18                                           T cell   4799
19                  alveolar type 1 fibroblast cell   4626