# Explore Metadata to isolate specific cell populations

for more informative or less confounded conclusions

In [1]:
# Load Meta Data
import os
import pandas as pd

save_path = '/media/rohola/ssd_storage/primary_metadata/'; print(len(os.listdir(save_path)))
files = sorted(os.listdir(save_path))
df = pd.concat([pd.read_pickle(save_path+f) for f in files], ignore_index=True)

36

In [8]:
int(0.7*len(df))

25025000

In [18]:
dtest = df[int(0.7*len(df)):]
#dtest = dtest[(dtest['cell_type'] == "epithelial cell") & (dtest['tissue_general'] == 'lung')]
dtest = dtest[(dtest['disease'] == "normal") & (dtest['tissue_general'] == 'lung')]
dtest.value_counts(subset=['cell_type']).reset_index().head(10)

                                    cell_type      0
0                         alveolar macrophage  43084
1  epithelial cell of lower respiratory tract  32786
2                                stromal cell  26855
3                          type II pneumocyte  23338
4                                 native cell  17948
5                            mesenchymal cell  12722
6                                  macrophage  12002
7                          classical monocyte  11981
8                         natural killer cell   7892
9                                    monocyte   7296

In [19]:
import scanpy as sc

an = sc.read_h5ad('/media/lleger/LaCie/mit/disease_geometry/attributions/' + 'Alzheimer disease_cells.h5ad')
an.obs['disease'].value_counts()

normal    50000
Name: disease, dtype: int64

In [12]:
df[(df['cell_type'] == "epithelial cell") & (df['tissue_general'] == 'lung')]['disease'].reset_index()[int(0.7*len(df)):].value_counts()

Series([], dtype: int64)

In [ ]:
df[(df['tissue_general'] == 'lung')]['disease'][:].value_counts()

In [5]:
project_path = "/media/lleger/LaCie/mit/disease_geometry/"
import json
diseases = json.load(open(project_path + 'diseases.json'))['diseases']
print(diseases)
#raise ValueError
diseases = ['small cell lung carcinoma', 'non-small cell lung carcinoma', 'glioblastoma', 'Parkinson disease', 'myocardial infarction', 'dilated cardiomyopathy']
for disease in diseases:
    print(disease)
    display(df[df['disease'] == disease][['cell_type', 'tissue_general']].value_counts().reset_index().head(10))

['normal', 'COVID-19', 'glioblastoma', 'dementia', 'lung adenocarcinoma', 'systemic lupus erythematosus', 'dilated cardiomyopathy', 'Crohn disease', 'clear cell renal carcinoma', 'squamous cell lung carcinoma', 'nonpapillary renal cell carcinoma', 'epilepsy', 'breast cancer', 'gastric cancer', 'non-small cell lung carcinoma', 'arrhythmogenic right ventricular cardiomyopathy', 'chronic kidney disease', 'acute kidney failure', 'follicular lymphoma', 'myocardial infarction', 'B-cell acute lymphoblastic leukemia', 'blastoma', 'Parkinson disease', 'B-cell non-Hodgkin lymphoma', 'plasma cell myeloma', 'respiratory system disorder', 'post-COVID-19 disorder', 'small cell lung carcinoma', 'pulmonary fibrosis', 'interstitial lung disease', 'digestive system disorder', 'periodontitis', 'Lewy body dementia', 'gastritis', 'gastric intestinal metaplasia', 'common variable immunodeficiency', 'benign prostatic hyperplasia', 'influenza', 'Crohn ileitis', 'pneumonia', 'pulmonary emphysema', 'chronic rhinitis', 'chronic obstructive pulmonary disease', 'kidney oncocytoma', 'type 2 diabetes mellitus', 'acute myeloid leukemia', 'trisomy 18', 'lung large cell carcinoma', 'Alzheimer disease', 'adenocarcinoma']
small cell lung carcinoma

         cell_type tissue_general      0
0  epithelial cell           lung  27326
1  epithelial cell     lymph node  16250
2           T cell          liver   7527
3  epithelial cell         axilla   6078
4  epithelial cell  pleural fluid   4650
5           T cell           lung   4040
6  epithelial cell  adrenal gland   3124
7           T cell  pleural fluid   2423
8           T cell     lymph node   1743
9  epithelial cell          liver   1287

non-small cell lung carcinoma

                         cell_type tissue_general      0
0  CD4-positive, alpha-beta T cell           lung  21395
1  CD8-positive, alpha-beta T cell           lung  17113
2                   malignant cell           lung  14143
3                       macrophage           lung  13537
4              alveolar macrophage           lung  10640
5                           B cell           lung   9175
6                      plasma cell           lung   8564
7                regulatory T cell           lung   8161
8              natural killer cell           lung   3971
9          epithelial cell of lung           lung   3789

glioblastoma

                        cell_type tissue_general       0
0                  malignant cell          brain  409290
1                      macrophage          brain  275761
2                 microglial cell          brain  205025
3                   mature T cell          brain  106256
4                        monocyte          brain   42646
5                 oligodendrocyte          brain   38983
6  oligodendrocyte precursor cell          brain   22555
7                  dendritic cell          brain    9616
8                      mural cell          brain    6142
9                endothelial cell          brain    5721

Parkinson disease

                        cell_type tissue_general      0
0                 oligodendrocyte          brain  69953
1                          neuron          brain  35776
2                       astrocyte          brain  12394
3                 microglial cell          brain  10156
4                endothelial cell          brain   5338
5  oligodendrocyte precursor cell          brain   4961
6             dopaminergic neuron          brain   2837

myocardial infarction

                                     cell_type tissue_general      0
0                      cardiac muscle myoblast          heart  50330
1                 fibroblast of cardiac tissue          heart  43717
2                     cardiac endothelial cell          heart  31904
3                immature innate lymphoid cell          heart  26664
4                                     pericyte          heart  10592
5  lymphoid lineage restricted progenitor cell          heart   5579
6                                  native cell          heart   3222
7                       smooth muscle myoblast          heart   2610
8                       neuronal receptor cell          heart   2008
9                                    mast cell          heart    597

dilated cardiomyopathy

                      cell_type tissue_general       0
0           cardiac muscle cell          heart  149631
1                    mural cell          heart   97754
2              endothelial cell          heart   83890
3  fibroblast of cardiac tissue          heart   83172
4                  myeloid cell          heart   40627
5                   native cell          heart   32258
6                    lymphocyte          heart   10661
7                cardiac neuron          heart    5922
8                      fat cell          heart     981
9                     mast cell          heart     542